apiVersion: v2
appVersion: "v1.0.0"
description: A ORY Kratos Helm chart for Kubernetes
name: kratos
icon: https://raw.githubusercontent.com/ory/docs/master/docs/static/img/logo-kratos.svg
version: 0.34.0
type: application
