apiVersion: v2
appVersion: "0.6.3-alpha.1"
description: A ORY Kratos Helm chart for Kubernetes
name: kratos
icon: https://raw.githubusercontent.com/ory/docs/master/docs/static/img/logo-kratos.svg
version: 0.19.4
type: application
