{{- include "hydra.automigration.typeVerification" . -}}
{{- if and  ( .Values.hydra.automigration.enabled ) ( eq .Values.hydra.automigration.type "job" ) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hydra.fullname" . }}-automigrate
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "hydra.labels" . | indent 4 }}
    {{- with .Values.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.job.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    helm.sh/hook-weight: "1"
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
spec:
  template:
    {{- with .Values.job.annotations }}
    metadata: 
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "hydra.job.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.job.automountServiceAccountToken }}
      containers:
      - name: {{ .Chart.Name }}-automigrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["hydra"]
        args: ["migrate", "sql", "-e", "--yes", "--config", "/etc/config/hydra.yaml"]
        env:
          - name: DSN
            valueFrom:
              secretKeyRef:
                name: {{ include "hydra.secretname" . }}
                key: dsn
        {{- with .Values.deployment.extraEnv }}
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- if .Values.job.lifecycle }}
        lifecycle:
{{ tpl .Values.job.lifecycle . | indent 10 }}
        {{- end }}
        {{- if .Values.deployment.securityContext }}
        securityContext:
          {{- toYaml .Values.deployment.securityContext | nindent 10 }}
        {{- end }}
        volumeMounts:
          - name: {{ include "hydra.name" . }}-config-volume
            mountPath: /etc/config
            readOnly: true
          {{- if .Values.deployment.extraVolumeMounts }}
            {{- toYaml .Values.deployment.extraVolumeMounts | nindent 10 }}
         {{- end }}
      {{- if .Values.job.extraInitContainers }}
      {{- if .Values.job.extraContainers }}
{{- tpl .Values.job.extraContainers . | nindent 6 }}
        {{- end }}
      initContainers:
        {{- tpl .Values.job.extraInitContainers . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      shareProcessNamespace: {{ .Values.job.shareProcessNamespace }}
      volumes:
        - name: {{ include "hydra.name" . }}-config-volume
          configMap:
            name: {{ include "hydra.fullname" . }}-migrate
        {{- if .Values.deployment.extraVolumes }}
          {{- toYaml .Values.deployment.extraVolumes | nindent 8 }}
        {{- end }}
  backoffLimit: {{ .Values.job.spec.backoffLimit }}
{{- end }}
