{{- $kubeVersion := .Capabilities.KubeVersion.GitVersion -}}
{{- $containerResourceAvailable := and (not (empty $kubeVersion)) (semverCompare ">=1.30.0" $kubeVersion) -}}
{{- $autoscaling := ternary .Values.deployment.autoscaling .Values.autoscaling (not (empty .Values.deployment.autoscaling )) -}}

{{- if and $autoscaling.enabled $containerResourceAvailable }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "keto.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "keto.labels" . | nindent 4 }}
spec:
  {{- with $autoscaling.behavior }}
  behavior: {{- toYaml . | nindent 4 }}
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "keto.fullname" . }}
  minReplicas: {{ $autoscaling.minReplicas }}
  maxReplicas: {{ $autoscaling.maxReplicas }}
  metrics:
  {{- with $autoscaling.targetMemory }}
  - type: ContainerResource
    containerResource:
      name: memory
      container: {{ $.Chart.Name }}
      target:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with $autoscaling.targetCPU}}
  - type: ContainerResource
    containerResource:
      name: cpu
      container: {{ $.Chart.Name }}
      target:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- if not (empty $autoscaling.extraMetrics) }}
  {{- toYaml $autoscaling.extraMetrics | nindent 2 }}
  {{- end }}
{{- end }}
