{{- if .Values.keto.autoMigrate }}
{{- $extraLabels := ternary .Values.deployment.extraLabels .Values.extraLabels (not (empty .Values.deployment.extraLabels )) -}}
{{- $extraVolumeMounts := ternary .Values.deployment.extraVolumeMounts .Values.extraVolumeMounts (not (empty .Values.deployment.extraVolumeMounts )) -}}
{{- $extraEnv := ternary .Values.deployment.extraEnv .Values.extraEnv (not (empty .Values.deployment.extraEnv )) -}}
{{- $extraVolumes := ternary .Values.deployment.extraVolumes .Values.extraVolumes (not (empty .Values.deployment.extraVolumes )) -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "keto.fullname" . }}-automigrate
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "keto.labels" . | indent 4 }}
    {{- with $extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.job.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    helm.sh/hook-weight: "1"
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
spec:
  template:
    metadata: 
      annotations:
      {{- with .Values.job.annotations }}  
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with $extraLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keto.job.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.job.automountServiceAccountToken }}
      containers:
      - name: {{ .Chart.Name }}-automigrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ "keto" ]
        args: [ "migrate", "up", "-y", "--config", "/etc/config/keto.yaml" ]
        {{- if .Values.job.lifecycle }}
{{ tpl .Values.job.lifecycle . | indent 8 }}
        {{- end }}
        volumeMounts:
          - name: {{ include "keto.name" . }}-config-volume
            mountPath: /etc/config
            readOnly: true
        {{- with $extraVolumeMounts }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
          - name: DSN
            valueFrom:
              secretKeyRef:
                name: {{ include "keto.secretname" . }}
                key: dsn
          {{- with $extraEnv }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- if .Values.securityContext }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        {{- end }}
      {{- if .Values.job.extraContainers }}
{{ tpl .Values.job.extraContainers . | indent 6 }}
      {{- end }}
      restartPolicy: Never
      volumes:
        - name: {{ include "keto.name" . }}-config-volume
          configMap:
            name: {{ include "keto.fullname" . }}-migrate
      {{- with $extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      shareProcessNamespace: {{ .Values.job.shareProcessNamespace }}
  backoffLimit: {{ .Values.job.spec.backoffLimit }}
{{- end }}
