apiVersion: v1
kind: Service
metadata:
  name: {{ include "keto.fullname" . }}-read
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "keto.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.read.type }}
  ports:
    - port: {{ .Values.service.read.port }}
      targetPort: read
      protocol: TCP
      name: read
  selector:
    app.kubernetes.io/name: {{ include "keto.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
