apiVersion: v2
# renovate: image=docker.io/oryd/hydra-maester
appVersion: "v0.0.38"
description: A Helm chart for Kubernetes
name: hydra-maester
icon: https://raw.githubusercontent.com/ory/docs/master/docs/static/img/logo-hydra.svg
version: 0.57.2
type: application
