apiVersion: v2
appVersion: "1.4.6"
description: A Helm chart for deploying the reference implementation for the User Login and Consent Flow in Kuberenetes
name: example-idp
version: 0.0.1
type: application
