apiVersion: v2
appVersion: "v2.0.1"
description: A Helm chart for deploying ORY Hydra in Kubernetes
name: hydra
icon: https://raw.githubusercontent.com/ory/docs/master/docs/static/img/logo-hydra.svg
version: 0.25.6
keywords:
  - oauth2
  - openid-connect
  - openid
  - oidc
  - op
  - api-security
  - security
home: https://www.ory.sh/
sources:
  - https://github.com/ory/hydra
  - https://github.com/ory/k8s
maintainers: # (optional)
  - name: ORY Team
    email: hi@ory.sh
    url: https://www.ory.sh/
type: application
dependencies:
  - name: hydra-maester
    version: 0.25.6
    condition: maester.enabled
    alias: hydra-maester
    repository: file://../hydra-maester
    # repository: https://k8s.ory.sh/helm/charts
