apiVersion: v1
appVersion: "v1.3.2+oryOS.17"
description: A Helm chart for deploying ORY Hydra in Kubernetes
name: hydra
version: 0.0.1
keywords:
  - oauth2
  - openid-connect
  - openid
  - oidc
  - op
  - api-security
  - security
home: https://www.ory.sh/
sources:
  - https://github.com/ory/hydra
  - https://github.com/ory/k8s
maintainers: # (optional)
  - name: ORY Team
    email: hi@ory.sh
    url: https://www.ory.sh/
