{{- if .Values.cronjob.cleanup.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kratos.cleanup.serviceAccountName" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "kratos.labels" . | nindent 4 }}
  {{- with .Values.cronjob.cleanup.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.cronjob.cleanup.serviceAccount.automountServiceAccountToken }}
{{- end -}}
