# Headless Service for StatefulSet. See https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations 
# and https://kubernetes.io/docs/concepts/services-networking/service/#headless-services for details.
{{- if .Values.courier.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kratos.fullname" . }}-courier
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/component: courier
    {{- include "kratos.labels" . | nindent 4 }}
    {{- with .Values.statefulSet.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.courier.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.statefulSet.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.courier.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.courier.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.courier.port }}
      targetPort: http-metrics
      protocol: TCP
      name: {{ .Values.service.courier.name }}
  selector:
    app.kubernetes.io/name: {{ include "kratos.name" . }}-courier
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if and (.Values.serviceMonitor.enabled) (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kratos.fullname" . }}-courier
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/component: courier
    {{- include "kratos.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.statefulSet.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.statefulSet.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - path: {{ .Values.service.courier.metricsPath }}
    port: {{ .Values.service.courier.name }}
    scheme: {{ .Values.serviceMonitor.scheme }}
    interval: {{ .Values.serviceMonitor.scrapeInterval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- with .Values.serviceMonitor.tlsConfig }}
    tlsConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kratos.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: courier
{{- end -}}
{{- end }}
